RIGHT seek  5
LEFT  seek -5
UP    seek  1
DOWN  seek -2
Shift+RIGHT seek 60
Shift+LEFT seek -60
ESC quit
ENTER cycle fullscreen
f cycle fullscreen
SPACE cycle pause
F11 add volume -1
F12 add volume 1
. add audio-delay 0.100
, add audio-delay -0.100
[ add sub-delay -1
] add sub-delay 1
< add speed -0.25
> add speed 0.25
Ctrl+1 set speed 1
Ctrl+2 set speed 1.5
Ctrl+3 set speed 2
Ctrl+4 set speed 3
Ctrl+5 set speed 4
Ctrl+6 set speed 16
Ctrl+7 set speed .5
l ab-loop
c cycle sub-visibility
x add sub-scale -0.1
v add sub-scale 0.1
